application: con-man
version: 1
runtime: python27
api_version: 1
threadsafe: true
libraries:
- name: ssl
  version: latest

handlers:
- url: /[\da-zA-Z-]+/api/.*
  script: api.api.app
- url: /[\da-zA-Z-]+/(.*\.(html|css|js|json))
  upload: client/.*\.(html|css|js|json)
  static_files: client/\1
- url: /[\da-zA-Z-]+/
  upload: client/index.html
  static_files: client/index.html
