application: con-man
version: 1
runtime: python27
api_version: 1
threadsafe: true
libraries:
- name: ssl
  version: latest

handlers:
- url: /.*/api/.*
  script: api.api.app
- url: /client/(.*\.(html|js|css))
  upload: client/.*\.(html|js|css)
  static_files: client/\1
- url: /.*
  upload: client/index.html
  static_files: client/index.html
